<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('settings')->delete();

        \DB::table('settings')->insert(array (
            0 =>
            array (
                'id' => 1,
                'key' => 'general-setting',
                'type' => 'general-setting',
                'value' => '{"site_name":"Spa Online","site_description":"Ra mắt Dịch vụ tại nhà theo yêu cầu trực tuyến trên thiết bị di động của riêng bạn với ứng dụng di động Spa Online. Các mẫu tùy chỉnh của ứng dụng tuyệt vời này có thể nhanh chóng cho phép các nhà phát triển thiết lập hệ thống đặt dịch vụ để chấp nhận đặt dịch vụ từ khách hàng từ bất kỳ đâu chỉ trong vài phút. Với trang Đăng nhập, trang Đăng ký, trang Phương thức thanh toán, danh sách Đặt chỗ, bản demo Loại dịch vụ, trang chi tiết Thợ sửa chữa, trang Phiếu giảm giá, v.v. đã sẵn sàng sử dụng, ứng dụng Spa Online này cho phép doanh nghiệp có ứng dụng hệ thống đặt dịch vụ hoàn chỉnh và đang hoạt động trong thời gian ngắn. Nhà cung cấp trong ứng dụng Spa Online này có thể chỉ định đặt chỗ cho Thợ sửa chữa và đẩy nhanh dịch vụ. Ứng dụng hệ thống Spa Online này đi kèm với bảng quản trị Laravel PHP để có thông tin chi tiết có ý nghĩa từ bảng điều khiển quản trị và số liệu thống kê. Chỉ định nhiều vai trò và quyền như Quản trị viên, Nhà cung cấp dịch vụ, Thợ sửa chữa và khách hàng bằng ứng dụng này. Ngoài ra, ứng dụng Dịch vụ Thợ sửa chữa này hỗ trợ hỗ trợ Nhiều ngôn ngữ/RTL. Ứng dụng có thể tùy chỉnh, sẵn sàng sử dụng này đi kèm với hỗ trợ chủ đề sáng và tối cũng như thông báo đẩy để tương tác với khách hàng theo cách tương tác hơn.","inquriy_email":"info@actcms.io.vn","helpline_number":"+84973909143","website":"https://actcms.io.vn/","country_id":"1","state_id":"50","city_id":"30","zipcode":"71000","address":"123 Đ. Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh, Việt Nam"}',
            ),
            1 =>
            array (
                'id' => 2,
                'key' => 'theme-setup',
                'type' => 'theme-setup',
                'value' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'key' => 'site-setup',
                'type' => 'site-setup',
                'value' =>'{"date_format":"F j, Y","time_format":"g:i A","time_zone":"Asia/Ho_Chi_Minh","language_option":["vi","en"],"default_currency":"1","currency_position":"right","google_map_keys":"AIzaSyCtTed7y_ePqg1QoDMHOyu01FtP_Ot-mDU","latitude":null,"longitude":null,"distance_type":"km","radious":"50","digitafter_decimal_point":"0","android_app_links":1,"playstore_url":"https://play.google.com/store/apps/details?id=io.actcms.spa.user","provider_playstore_url":"https://play.google.com/store/apps/details?id=io.actcms.spa.vendor","ios_app_links":1,"appstore_url":"https://apps.apple.com/vn/app/market-online/id6472641956","provider_appstore_url":"https://apps.apple.com/vn/app/it-home-dịch-vụ-tại-nhà/id6484594491","site_copyright":"© 2024 All Rights Reserved by ACTCMS Vietnam"}',
            ),
            3 =>
            array (
                'id' => 4,
                'key' => 'service-configurations',
                'type' => 'service-configurations',
                'value' =>'{"advance_payment":1,"slot_service":1,"digital_services":1,"service_packages":1,"service_addons":1,"post_services":1}',
            ),
            4 =>
            array (
                'id' => 5,
                'key' => 'OTHER_SETTING',
                'type' => 'OTHER_SETTING',
                'value' => '{"social_login":1,"google_login":1,"apple_login":1,"otp_login":1,"online_payment":1,"blog":1,"maintenance_mode":0,"wallet":1,"enable_chat_gpt":1,"test_without_key":1,"chat_gpt_key":null,"force_update_user_app":0,"user_app_minimum_version":null,"user_app_latest_version":null,"force_update_provider_app":0,"provider_app_minimum_version":null,"provider_app_latest_version":null,"force_update_admin_app":0,"admin_app_minimum_version":null,"admin_app_latest_version":null,"firebase_notification":1,"project_id":"AAAAZhoeujI:APA91bFqbSHVjdMFGQT7G4C3cSczXeuXExsps__EtX_GlyUTleotEuOceprwFvvDOZ-4ay7rUIZ1R7tZ9BXtQuZhMUnOP_kRfRkPUOzdlHacCyRdwrUKAlQf7xkKWgdJeJgAybRavN3O","auto_assign_provider":0, "dashboard_type":"dashboard"}',
            ),
            5 =>
            array (
                'id' => 6,
                'key' => 'social-media',
                'type' => 'social-media',
                'value' => '{"facebook_url":"https://www.facebook.com/actcmsvn/","linkedin_url":"https://www.linkedin.com/company/actcmsvn/","instagram_url":"https://www.instagram.com/actcmsvn/","youtube_url":"https://www.youtube.com/actcmsvn","twitter_url":"https://twitter.com/actcmsvn"}',
            ),


            6 =>
            array (
                'id' => 7,
                'key' => 'terms_condition',
                'type' => 'terms_condition',
            'value' => '<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">By accessing products on this site and placing an order from our website, you confirm that you are in agreement with and bound by the terms and conditions presented and outlined here. These terms apply to the entire website and any email or other type of communication between you and ACTCMS Vietnam. The ACTCMS Vietnam team is not liable for any direct, indirect, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use the materials on this site.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />ACTCMS Vietnam will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Products</span></h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">All products and services offered on this site are produced by ACTCMS Vietnam. You can access your download from your respective dashboard. We do not provide support for 3rd party software, plugins or libraries that you might have used with our products.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Security</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">ACTCMS Vietnam does not process any order payments through the website. All payments are processed securely through RazorPay and Stripe, a third party online payment providers.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Cookie Policy</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server. Our website uses cookies. By using our website and agreeing to this policy, you consent to our use of cookies in accordance with the terms of this policy.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />We use session cookies to personalize the website for each user.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />We use Google Analytics to analyze the use of our website. Our analytics service provider generates statistical and other information about website use by means of cookies. Deleting cookies will have a negative impact on the usability of the site. If you block cookies, you will not be able to use all the features on our website.<br /><br /></p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Refunds</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">You can ask for refund against the item purchased under certain circumstances listed in our Refund Policy. In the event that you meet the applicable mark for receiving refund, ACTCMS Vietnam will issue you a refund and ask you to specify how the product turned down your item performance expectations.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Email</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">By signing up on our website https://actcms.io.vn you agree to receive emails from us &ndash; Transactional as well as promotional (occasional).</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Ownership</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Ownership of the product is governed by the usage license.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Changes about terms</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We may change/update our terms of use without any prior notice. If we change our terms and condition, we will post those changes on this page. Users can check latest version in here.</p>
<p>&nbsp;</p>',
            ),
            7 =>
            array (
                'id' => 8,
                'key' => 'privacy_policy',
                'type' => 'privacy_policy',
            'value' => '<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">This Privacy Policy is brought by ACTCMS Vietnam. ACTCMS Vietnam is the sole owner of a number of demo websites containing previews of WordPress website themes. This Privacy Policy shall apply to all ACTCMS Vietnam sites where this Privacy Policy is featured. This Privacy Policy describes how the ACTCMS Vietnam collects, uses, shares and secures personal information that you provide.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">ACTCMS Vietnam does not share personal information of any kind with anyone. We will not sell or rent your name or personal information to any third party. We do not sell, rent or provide outside access to our mailing list or any data we store. Any data that a user stores via our facilities is wholly owned by that user or business. At any time, a user or business is free to take their data and leave, or to simply delete their data from our facilities.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">ACTCMS Vietnam only collects specific personal information that is necessary for you to access and use our services. This personal information includes, but is not limited to, first and last name, email address, Country of residence.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">ACTCMS Vietnam may release personal information if ACTCMS Vietnam is required to by law, search warrant, subpoena, court order or fraud investigation. We may also use personal information in a manner that does not identify you specifically nor allow you to be contacted but does identify certain criteria about our site&rsquo;s users in general (such as we may inform third parties about the number of registered users, number of unique visitors, and the pages most frequently browsed).</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">&nbsp;</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Use of Information</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We use the information to enable your use of the site and its features and to assure security of use and prevent any potential abuse. We may use the information that we collect for a variety of purposes including:</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Promotion</span>&nbsp;&mdash; With your consent we send promotional communications, such as providing you with information about products and services, features, surveys, newsletters, offers, promotions, contests and events;</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Safety and security</span>&nbsp;&mdash; We use the information we have to verify accounts and activities, combat harmful conduct, detect and prevent spam and other bad experiences, maintain the integrity of the Platform, and promote safety and security.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Product research and development</span>&nbsp;&mdash; We use the information we have to develop, test and improve our Platform and Services, by conducting surveys and research, and testing and troubleshooting new products and features.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Communication with you</span>&nbsp;&mdash; We use the information we have to send you various communications, communicate with you about our products, and let you know about our policies and terms. We also use your information to respond to you when you contact us.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">&nbsp;</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Amendments</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We may amend this Privacy Policy from time to time. When we amend this Privacy Policy, we will update this page accordingly and require you to accept the amendments in order to be permitted to continue using our services.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;"><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />Contact Us</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">You can learn more about how privacy works within our site by contacting us. If you have questions about this Policy, you can contact us via email address provided. Additionally, we may also resolve any disputes you have with us in connection with our privacy policies and practices through direct contact. Write to us at&nbsp;<span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; transition: all 0.5s ease-in-out 0s; text-decoration-line: underline;"><em style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;">info@actcms.io.vn</em></span></p>
<p>&nbsp;</p>',
            ),
            8 =>
            array (
                'id' => 9,
                'key' => 'refund_cancellation_policy',
                'type' => 'refund_cancellation_policy',
                'value' => '<p dir="ltr">At Handyman, we are committed to providing you with high-quality services that meet your needs and exceed your expectations. However, we understand that things do not always go according to plan, and sometimes cancellations or refunds might be necessary. This policy outlines the circumstances under which you can request a refund or cancel a booking made through the Handyman mobile app.</p>
                            <p dir="ltr"><strong>Cancellations &amp; :</strong></p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Unavailability of Handyman: You can cancel any booking free of charge until the provider accepts it. To cancel, open the Handyman Customer App, navigate to your booking details, and tap "Cancel Booking." If you cancel before the provider accepts your booking, you will receive a full refund of the service fee for advance booking services.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Unavailability of Handyman: In the rare event that a Handyman is unable to make it to your scheduled appointment due to unforeseen circumstances, the provider can decline your service.</p>
                            </li>
                            </ul>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Reschedule your appointment: We will work with you to find a new appointment time that suits your needs.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Cancel your booking and receive a full refund: No cancellation fee will be applied (If this service is based on advance booking service).</p>
                            </li>
                            </ul>
                            <p><strong>Refunds:</strong></p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Refunds will be processed into the users wallet if this service is based on Advance booking service.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">The following situations are not eligible for a full refund:&nbsp;</p>
                            </li>
                            </ul>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You cancel your booking before the provider accepts it.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You are not satisfied with the quality of the work performed, but the Handyman completed the service as described in the app.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You experience minor inconveniences or delays during the service.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You request changes to the scope of the service after the Handyman has arrived, which may result in additional charges.</p>
                            </li>
                            </ul>
                            <p dir="ltr"><strong>Dispute Resolution:</strong></p>
                            <p dir="ltr">If you have any concerns or disagreements regarding your refund or cancellation request, please contact Handyman customer support at <a href="mailto:info@actcms.io.vn">info@actcms.io.vn</a> or call us at +84973909143. We are committed to resolving all issues fairly and amicably.</p>
                            <p dir="ltr">Important Notes:&nbsp;</p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">This Refund and Cancellation Policy applies to all bookings made through the Handyman App or Website.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Handyman reserves the right to modify this policy at any time without prior notice. The latest version of this policy will always be available on the Handyman website and mobile app.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">By using the Handyman mobile app, you agree to be bound by this Refund and Cancellation Policy.</p>
                            </li>
                            </ul>
                            <p dir="ltr">We hope this policy clarifies the process for requesting refunds and cancellations on the Handyman app. If you have any questions, please feel free to contact our customer support team.</p>
                            <p>&nbsp;</p>
                            <p dir="ltr">Sincerely,</p>
                            <p dir="ltr">ACTCMS Vietnam</p>',
            ),
            9 =>
            array (
                'id' => 10,
                'key' => 'help_support',
                'type' => 'help_support',
                'value' => '<p>Contact Us for Support</p>
                            <p>Email</p>
                            <p>Email us at : info@actcms.io.vn<br /><br />Telephone</p>
                            <p>Call us at : +84973909143<br /><br />Additional Information</p>
                            <p>If you need further assistance or have specific inquiries, feel free to reach out through the provided contact options.</p>',
            ),
            10 =>
            array (
                'id' => 11,
                'key' => 'cookie-setup',
                'type' => 'cookie-setup',
                'value' => '{"title":"Thông báo về cookie","description":"Chúng tôi sử dụng cookie để duyệt tốt hơn, nội dung được cá nhân hóa và phân tích lưu lượng truy cập. Nhấp vào `Chấp nhận tất cả` để đồng ý."}',
            ),
            11 =>
            array (
                'id' => 12,
                'key' => 'earning-setting',
                'type' => 'earning-setting',
                'value' => 'commission',
            ),
            12 =>
                        array (
                            'id' => 13,
                            'key' => 'data_deletion_request',
                            'type' => 'data_deletion_request',
                            'value' => '<p dir="ltr">To ensure the safety and privacy of your data, we offer a streamlined process for requesting its removal from our servers. To initiate the deletion process, kindly send an email from your registered email address to our dedicated email inbox at <strong>info@actcms.io.vn</strong> Upon based on your request, our team will thoroughly examine the provided details and proceed with necessary actions in adherence to our privacy policies and legal obligations.  </p>
                            <p>&nbsp;</p>
                            <p dir="ltr">Sincerely,</p>
                            <p dir="ltr">ACTCMS Vietnam</p>',
            ),

        ));


    }
}
